// Copy pasted from Spades internals, replace with studios-dev/router once it's released - Bloxs

// Ract Router v2 by ract-team@Studios
import { readFileSync } from "node:fs";
import { readdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";
import process from "node:process";
import { type RouteObject } from "react-router";
import { type PluginOption } from "vite";

export interface RouteOutput {
	path?: string;
	element?: string;
	errorElement?: string;
	children?: RouteOutput[];
}

/**
 * @param {string} routesPath - ./src/app/routes
 * @param {string} exportPath - ./src/app/router.tsx
 */
export default function routerBuilder({
	routesPath,
	exportPath,
}: {
	routesPath: string;
	exportPath: string;
}): PluginOption {
	const routePathFull = join(process.cwd(), routesPath);
	const exportPathFull = join(process.cwd(), exportPath);
	let output = readFileSync(exportPathFull, "utf-8");

	// Because thanks microsoft
	const windowsIssue = (path: string) => path.replace(/\\/g, "/");

	const buildRouteData = async () => {
		const routes: RouteObject[] = [];

		let index = 0;
		const filePathToIndex: Record<string, number> = {};

		const getIndexForPath = (path: string) => {
			if (filePathToIndex[path]) return `$${filePathToIndex[path]}`;

			filePathToIndex[path] = index++;

			return `$${index - 1}`;
		};

		const recursivelyWalkPaths = async (
			path: string,
			parent: RouteObject[] = routes,
		) => {
			const relativePath = windowsIssue(relative(routePathFull, path))
				.split("/")
				.filter((x) => !/^\(.*\)$/.test(x))
				.map((x) =>
					/^\[.*\]$/.test(x)
						? x.replace(
								/^\[.*\]$/,
								(match) =>
									`:${match.substring(1, match.length - 1)}`,
							)
						: x,
				)
				.join("/");
			const files = (await readdir(path)).sort();
			const components = files.filter(
				(x) =>
					x.endsWith(".tsx") &&
					["page", "not-found", "layout", "error"]
						.map((x) => `${x}.tsx`.toLowerCase())
						.includes(x.toLowerCase()),
			);
			const folders = files.filter((x) => !x.endsWith(".tsx"));

			const routeObject: RouteOutput = {};

			if (components.length > 0) {
				if (components.includes("layout.tsx")) {
					const index = getIndexForPath(
						windowsIssue(join(path, "layout.tsx")),
					);

					const obj: RouteOutput = {
						element: index,
						children: [],
					};

					parent.push(obj);
					parent = obj.children!;
				}

				const includes = (
					name: string,
					callback: (index: string) => void,
				) => {
					if (components.includes(name)) {
						const index = getIndexForPath(
							windowsIssue(join(path, name)),
						);

						callback(index);
					}
				};

				includes("page.tsx", (index) => {
					routeObject.element = index;
					routeObject.path = windowsIssue(join(relativePath, "/"));
				});

				includes("error.tsx", (index) => {
					routeObject.errorElement = index;
				});

				includes("not-found.tsx", (index) => {
					parent.push({
						element: index,
						path: windowsIssue(join(relativePath, "./*")),
					});
				});

				if (JSON.stringify(routeObject) !== "{}") {
					parent.push(routeObject);
				}
			}

			for (const folder of folders) {
				const folderPath = windowsIssue(join(path, folder));

				await recursivelyWalkPaths(folderPath, parent);
			}
		};

		await recursivelyWalkPaths(routePathFull);
		const outputRouteString = JSON.stringify(routes, null, 4)
			.replace(/"\$[0-9]{1,}"/g, (match) => {
				const val = match.substring(1, match.length - 1);
				return `<${val} />`;
			})
			.replace(
				/"(path|element|errorElement|children)":/g,
				(match) => `${match.substring(1, match.length - 2)}:`,
			);

		const importPrefix = relative(exportPathFull, routePathFull)
			.replace(/\\/g, "/")
			.substring(1);

		const importsString = Object.entries(filePathToIndex)
			.map(([path, index]) => {
				return `import $${index} from "./${join(
					importPrefix,
					`./${windowsIssue(relative(routePathFull, path))}`,
				).replace(/\\/g, "/")}";`;
			})
			.join("\n");

		const fullExport = [
			"// !! DO NOT MODIFY THIS !! YOUR CHANGES WILL BE OVERWRITTEN !!",
			'import { createBrowserRouter } from "react-router";',
			"",
			importsString,
			"",
			"// Generated by Ract Router",
			`const routes = ${outputRouteString};`,
			"",
			`const router = createBrowserRouter(routes);`,
			"",
			"export { routes, router };",
		].join("\n");

		if (fullExport != output) {
			output = fullExport;
			await writeFile(exportPathFull, output);
			console.log("Updated routes");
		}
	};

	return {
		name: "ract-router",
		async buildStart() {
			await buildRouteData();
		},
		async watchChange(id: string) {
			const relativePath = relative(routePathFull, id);

			if (relativePath.startsWith("..")) return;

			await buildRouteData();
		},
	};
}