// !! DO NOT MODIFY THIS !! YOUR CHANGES WILL BE OVERWRITTEN !!
import { createBrowserRouter } from "react-router";

import $0 from "./app/page.tsx";

// Generated by Ract Router
const routes = [
    {
        element: <$0 />,
        path: "/"
    }
];

const router = createBrowserRouter(routes);

export { routes, router };